export const ORCHESTRATOR_AGENTS = Object.freeze({
  planner: {
    type: "planner",
    name: "Planning Agent",
    systemPrompt: "Decompose complex goals into safe, ordered, executable tasks with dependencies.",
    toolPermissions: [],
    memoryScopes: ["workspace", "project", "conversation"],
  },
  executor: {
    type: "executor",
    name: "Execution Agent",
    systemPrompt: "Execute approved steps, coordinate tools, track progress, and report precise completion state.",
    toolPermissions: ["workflow.execute", "api.request"],
    memoryScopes: ["workspace", "project", "execution"],
  },
  researcher: {
    type: "researcher",
    name: "Research Agent",
    systemPrompt: "Research, extract, compare, and cite relevant information. Prefer tool-backed browsing when needed.",
    toolPermissions: ["browser.search", "browser.navigate", "api.request"],
    memoryScopes: ["workspace", "project", "semantic"],
  },
  coder: {
    type: "coder",
    name: "Coding Agent",
    systemPrompt: "Write, refactor, review, and explain production code. Use app generation and code execution tools when appropriate.",
    toolPermissions: ["app.generate", "code.execute", "filesystem.read"],
    memoryScopes: ["workspace", "project", "execution"],
  },
  assistant: {
    type: "assistant",
    name: "AI Assistant Agent",
    systemPrompt: "Assist users with workspace tasks, summarize runtime state, and route requests to specialized agents.",
    toolPermissions: ["api.request"],
    memoryScopes: ["workspace", "conversation", "user"],
  },
  content_generator: {
    type: "content_generator",
    name: "Content Generator Agent",
    systemPrompt: "Generate, revise, and package high-quality content using available model and media runtimes.",
    toolPermissions: ["api.request"],
    memoryScopes: ["workspace", "project", "semantic"],
  },
  debugging: {
    type: "debugging",
    name: "Debugging Agent",
    systemPrompt: "Diagnose failed executions, identify the smallest safe repair, and produce actionable recovery steps before retrying.",
    toolPermissions: ["code.execute", "filesystem.read", "api.request"],
    memoryScopes: ["workspace", "project", "execution"],
  },
  browser: {
    type: "browser",
    name: "Browser Agent",
    systemPrompt: "Navigate websites, extract data, fill safe forms, and capture screenshots. Do not bypass captchas.",
    toolPermissions: ["browser.search", "browser.navigate", "browser.click", "browser.fill", "browser.workflow"],
    memoryScopes: ["workspace", "project", "browser"],
  },
  deployment: {
    type: "deployment",
    name: "Deployment Agent",
    systemPrompt: "Prepare deployment plans, Docker configs, and deployment diagnostics. Require approval for external deploys.",
    toolPermissions: ["api.request", "terminal.exec"],
    memoryScopes: ["workspace", "project", "deployment"],
  },
  memory: {
    type: "memory",
    name: "Memory Agent",
    systemPrompt: "Summarize executions and maintain useful long-term memory with sensitivity awareness.",
    toolPermissions: [],
    memoryScopes: ["workspace", "project", "semantic", "relationship"],
  },
  analytics: {
    type: "analytics",
    name: "Analytics Agent",
    systemPrompt: "Analyze runtime metrics, failures, cost, latency, and execution quality.",
    toolPermissions: ["api.request"],
    memoryScopes: ["workspace", "execution"],
  },
  runtime: {
    type: "runtime",
    name: "Runtime Agent",
    systemPrompt: "Inspect runtime diagnostics, queues, workers, providers, and local open-source runtime availability.",
    toolPermissions: ["api.request"],
    memoryScopes: ["workspace", "execution"],
  },
  monitoring: {
    type: "monitoring",
    name: "Monitoring Agent",
    systemPrompt: "Observe health signals, detect degraded runtime paths, and recommend recovery actions.",
    toolPermissions: ["api.request"],
    memoryScopes: ["workspace", "execution"],
  },
  file_manager: {
    type: "file_manager",
    name: "File Management Agent",
    systemPrompt: "Inspect uploaded files, generated project files, and knowledge base chunks.",
    toolPermissions: ["filesystem.read"],
    memoryScopes: ["workspace", "project", "files"],
  },
  api_integration: {
    type: "api_integration",
    name: "API Integration Agent",
    systemPrompt: "Design, call, validate, and troubleshoot APIs with safe request policies.",
    toolPermissions: ["api.request"],
    memoryScopes: ["workspace", "project"],
  },
});
