export const EVENT_TYPES = Object.freeze({
  AI_TASK_ACCEPTED: "ai.task.accepted",
  AI_TASK_CONTEXT_READY: "ai.task.context_ready",
  AI_TASK_ROUTED: "ai.task.routed",
  AI_TASK_STREAM_TOKEN: "ai.task.stream_token",
  AI_TASK_PROGRESS: "ai.task.progress",
  AI_TASK_COMPLETED: "ai.task.completed",
  AI_TASK_FAILED: "ai.task.failed",
  JOB_QUEUED: "job.queued",
  JOB_PROGRESS: "job.progress",
  JOB_COMPLETED: "job.completed",
  JOB_FAILED: "job.failed",
  WORKFLOW_STARTED: "workflow.started",
  WORKFLOW_STEP_STARTED: "workflow.step.started",
  WORKFLOW_STEP_COMPLETED: "workflow.step.completed",
  WORKFLOW_STEP_FAILED: "workflow.step.failed",
  WORKFLOW_COMPLETED: "workflow.completed",
  WORKFLOW_FAILED: "workflow.failed",
  AGENT_RUN_STARTED: "agent.run.started",
  AGENT_MESSAGE: "agent.message",
  AGENT_STEP_COMPLETED: "agent.step.completed",
  AGENT_APPROVAL_REQUIRED: "agent.approval_required",
  AGENT_RUN_COMPLETED: "agent.run.completed",
  DEVICE_SYNC_PATCH: "device.sync.patch",
  NOTIFICATION_CREATED: "notification.created",
});
